gabymg26/Rep-SportGear

src/main/java/com/sportgear/sportgear/Security/SecurityConfiguration.java
src/main/resources/templates/listar_inventario.html

[ X] Add username al inicio de sesión.

Add username al iniciar sesión

---

src/main/resources/application.properties
src/main/resources/templates/listar_inventario.html

[X] Changing Style Username Admin

Changing Style Username Admin

---

src/main/resources/application.properties
src/main/resources/templates/crear_categoria.html
src/main/resources/templates/crear_implemento.html
src/main/resources/templates/listar_inventario.html

Changing style, background y botón de los formularios
1) Formulario de crear nueva categoría
2) Formulario de crear nuevo implemento

Changing style, background y botón de los formularios

---

src/main/java/com/sportgear/sportgear/Controller/CategoriaController.java
src/main/java/com/sportgear/sportgear/Service/CatImplementosService.java
src/main/java/com/sportgear/sportgear/Service/CatImplementosServiceImpl.java
src/main/resources/templates/listarCategorias.html
src/main/resources/templates/listar_inventario.html

[X] Changing Style ListarCategorias
[X] Update CategoriaController, CategoriaService, CategoriaServiceImpl

Changing Style y Update ListarCategorias y CategoriaController

---

src/main/java/com/sportgear/sportgear/Controller/CategoriaController.java
src/main/resources/templates/crear_categoria.html

[X] Changing Style Formulario Crear Categoria
[X] Update Titulo del Formulario desde el CategoriaController

Changing Style y Update CrearCategoria, CategoriaController

---

src/main/resources/templates/registro.html

[X] Changing Style Selector de Rol

Changing Style Select del Registro

---

src/main/resources/templates/crear_categoria.html
src/main/resources/templates/crear_implemento.html
src/main/resources/templates/listarCategorias.html
src/main/resources/templates/listar_inventario.html

[X] Update utilización bootstrap del header en paginas del Admin

Update utilización bootstrap del header en paginas del Admin

---

src/main/java/com/sportgear/sportgear/Controller/InventarioController.java

[X] Update titulo Editar Implemento

Update titulo Editar Implemento

---

src/main/java/com/sportgear/sportgear/Controller/InventarioController.java
src/main/resources/application.properties
src/main/resources/templates/listar_inventario.html
src/main/resources/templates/registro.html

[X] Changing style corrigiendo ortografía

Changing style corrigiendo ortografía

---

src/main/resources/templates/listar_inventario.html

Add alert info

---

src/main/java/com/sportgear/sportgear/Controller/InventarioController.java
src/main/java/com/sportgear/sportgear/Model/Estado.java
src/main/java/com/sportgear/sportgear/Model/Inventario.java
src/main/java/com/sportgear/sportgear/Repository/EstadosRepository.java
src/main/java/com/sportgear/sportgear/Service/EstadosService.java
src/main/java/com/sportgear/sportgear/Service/EstadosServiceImpl.java
src/main/resources/templates/crear_implemento.html

[X] Add clase,repository,service,serviceImpl Estado

Add clase,repository,service,serviceImpl Estado

---

src/main/resources/templates/crear_categoria.html
src/main/resources/templates/crear_implemento.html
src/main/resources/templates/listarCategorias.html

[X] Add alert info a todas las plantillas

Add alert info a todas las plantillas

---

src/main/resources/application.properties
src/main/resources/templates/listar_inventario.html
src/main/resources/templates/login.html
src/main/resources/templates/registro.html

[X] Fixed bug de la imagen del Login y Registrarse y al listar el estado

Fixed bug de la imagen del Login y Registrarse y al listar el estado

---

src/main/java/com/sportgear/sportgear/Service/Impl/CatImplementosServiceImpl.java
src/main/java/com/sportgear/sportgear/Service/Impl/EstadosServiceImpl.java
src/main/java/com/sportgear/sportgear/Service/Impl/InventarioServiceImpl.java
src/main/java/com/sportgear/sportgear/Service/Impl/UsuarioServicioImpl.java

[X] Add carpeta de Implementaciones en los servicios

Add carpeta de Implementaciones en los servicios

---

src/main/resources/templates/login.html
src/main/resources/templates/registro.html

[X] Update Imagen Login y Registro Usco

Update Imagen Login y Registro Usco

---

src/main/java/com/sportgear/sportgear/Controller/CategoriaController.java
src/main/java/com/sportgear/sportgear/Controller/InventarioController.java
src/main/java/com/sportgear/sportgear/Model/Prestamos.java
src/main/java/com/sportgear/sportgear/Security/SecurityConfiguration.java
src/main/resources/application.properties
src/main/resources/templates/crear_categoria.html
src/main/resources/templates/crear_implemento.html
src/main/resources/templates/listarCategorias.html
src/main/resources/templates/listar_inventario.html

[X] Add requestMapping /administrador a todo lo del admin

Add requestMapping /administrador a todo lo del admin

---

src/main/java/com/sportgear/sportgear/Controller/InventarioController.java
src/main/java/com/sportgear/sportgear/Model/Inventario.java
src/main/java/com/sportgear/sportgear/Service/Impl/InventarioServiceImpl.java
src/main/resources/application.properties
src/main/resources/static/Scripts/Switch.js
src/main/resources/templates/crear_categoria.html
src/main/resources/templates/crear_implemento.html
src/main/resources/templates/listarCategorias.html
src/main/resources/templates/listar_inventario.html

Add archivos

---

src/main/resources/templates/crear_categoria.html

[X] Update utilización de unas clases de bootstrap en crear_categoria

Update utilización de unas clases de bootstrap en crear_categoria

---

src/main/resources/templates/listar_inventario.html

[X] Changing Style imagen de Editar en listar_inventario

Changing Style imagen de Editar en listar_inventario

---

src/main/java/com/sportgear/sportgear/Controller/EstudianteController.java
src/main/java/com/sportgear/sportgear/Controller/dto/UsuarioRegistroDTO.java
src/main/java/com/sportgear/sportgear/Model/Rol.java
src/main/java/com/sportgear/sportgear/Model/Usuario.java
src/main/java/com/sportgear/sportgear/Repository/UsuarioRepositorio.java
src/main/java/com/sportgear/sportgear/Security/SecurityConfiguration.java
src/main/java/com/sportgear/sportgear/Service/Impl/UsuarioServicioImpl.java
src/main/java/com/sportgear/sportgear/Service/UsuarioServicio.java
src/main/resources/templates/panel.html

[X] Update espaciados
[X] Add archivos estudiante

Update espaciados y Add archivos estudiante

---

pom.xml
src/main/java/com/sportgear/sportgear/Controller/EstudianteController.java
src/main/java/com/sportgear/sportgear/Model/Prestamos.java
src/main/java/com/sportgear/sportgear/Repository/PrestamoRepository.java
src/main/java/com/sportgear/sportgear/Security/SecurityConfiguration.java
src/main/java/com/sportgear/sportgear/Service/Impl/PrestamosServiceImpl.java
src/main/java/com/sportgear/sportgear/Service/PrestamosService.java
src/main/resources/static/Scripts/Categoria.js
src/main/resources/static/Scripts/Estado.js
src/main/resources/templates/solicitud.html

[X] Add logica Prestamos
[X] Update Security

Add logica Prestamos y Update Security

---

src/main/java/com/sportgear/sportgear/Controller/CategoriaController.java
src/main/java/com/sportgear/sportgear/Controller/EstudianteController.java
src/main/java/com/sportgear/sportgear/Controller/InventarioController.java
src/main/java/com/sportgear/sportgear/Security/SecurityConfiguration.java
src/main/resources/templates/crear_categoria.html
src/main/resources/templates/crear_implemento.html
src/main/resources/templates/listarCategorias.html
src/main/resources/templates/listar_inventario.html
src/main/resources/templates/panel.html

Update detalles de rutas

---

src/main/java/com/sportgear/sportgear/Controller/InventarioController.java
src/main/resources/application.properties
src/main/resources/templates/crear_implemento.html

Fixed Disponible switch

---

src/main/resources/application.properties
src/main/resources/templates/crear_implemento.html

[X] Fixed ruta de guardado en crear_implemento

Fixed ruta de guardado en crear_implemento

---

src/main/java/com/sportgear/sportgear/Controller/EstudianteController.java
src/main/resources/templates/listar_inventario.html
src/main/resources/templates/panel.html

[X] Add paginación estudiantes 
[X]  Changing Style paginación de Admin

Add paginación estudiantes y Changing Style paginación de Admin

---

src/main/java/com/sportgear/sportgear/Model/Devoluciones.java
src/main/resources/static/Scripts/DevolucionCategoria.js
src/main/resources/static/Scripts/Estado.js
src/main/resources/static/Scripts/SolicitudCargaDom.js
src/main/resources/static/Scripts/SolicitudCategoria.js
src/main/resources/templates/devolucion.html
src/main/resources/templates/solicitud.html

[X] Update cargas del Dom en solicitud
[X] Update cargas del Dom en devolucion

Update cargas del Dom en solicitud y devolucion

---

src/main/java/com/sportgear/sportgear/Controller/RegistroUsuarioControlador.java
src/main/java/com/sportgear/sportgear/Security/SecurityConfiguration.java
src/main/java/com/sportgear/sportgear/Service/Impl/UsuarioServicioImpl.java
src/main/resources/application.properties
src/main/resources/templates/devolucion.html
src/main/resources/templates/solicitud.html

Fixed NombreUsuario

---

src/main/java/com/sportgear/sportgear/Model/Devoluciones.java
src/main/java/com/sportgear/sportgear/Model/Prestamos.java
src/main/resources/application.properties

[X] Fixed quitando nombreUsuario de Prestamos y Devoluciones

Fixed quitando nombreUsuario de Prestamos y Devoluciones

---

src/main/resources/templates/crear_categoria.html
src/main/resources/templates/crear_implemento.html
src/main/resources/templates/devolucion.html
src/main/resources/templates/listarCategorias.html
src/main/resources/templates/listar_inventario.html
src/main/resources/templates/panel.html
src/main/resources/templates/solicitud.html

[X] Add nombre de usuario a todas las paginas

Add nombre de usuario a todas las paginas

---

src/main/java/com/sportgear/sportgear/Controller/CategoriaController.java
src/main/java/com/sportgear/sportgear/Controller/InventarioController.java
src/main/java/com/sportgear/sportgear/Security/SecurityConfiguration.java
src/main/resources/templates/crearCategoria.html
src/main/resources/templates/crearImplemento.html
src/main/resources/templates/listarDevoluciones.html
src/main/resources/templates/listarInventario.html
src/main/resources/templates/listarPrestamos.html

[X] Update rutas
[X] Add seccion de seguimiento

Update rutas y Add seccion de seguimiento

---

src/main/java/com/sportgear/sportgear/Model/Devoluciones.java
src/main/java/com/sportgear/sportgear/Model/Prestamos.java
src/main/resources/templates/listarInventario.html
src/main/resources/templates/panel.html

Update tittles paginas

---

src/main/resources/templates/devolucion.html
src/main/resources/templates/panel.html
src/main/resources/templates/solicitud.html

[X] Update formato Imagenes en Panel de Control Estudiantes

Update formato Imagenes en Panel de Control Estudiantes

---

src/main/java/com/sportgear/sportgear/Controller/RegistroUsuarioControlador.java
src/main/resources/templates/login.html
src/main/resources/templates/registro.html

[X] Update formato Imagenes en Login y Registro a SVG

Update formato Imagenes en Login y Registro a SVG

---

src/main/java/com/sportgear/sportgear/Model/Prestamos.java
src/main/resources/application.properties
src/main/resources/templates/solicitud.html

Guardando nombre

---

src/main/java/com/sportgear/sportgear/Controller/EstudianteController.java
src/main/resources/application.properties
src/main/resources/templates/devolucion.html

[X] Add guardar nombre en Devoluciones

Add guardar nombre en Devoluciones

---

src/main/java/com/sportgear/sportgear/Controller/DevolucionesController.java
src/main/java/com/sportgear/sportgear/Controller/PrestamosController.java
src/main/java/com/sportgear/sportgear/Service/DevolucionesService.java
src/main/java/com/sportgear/sportgear/Service/Impl/DevolucionesServiceImpl.java
src/main/java/com/sportgear/sportgear/Service/Impl/EstadosServiceImpl.java
src/main/java/com/sportgear/sportgear/Service/Impl/PrestamosServiceImpl.java
src/main/java/com/sportgear/sportgear/Service/PrestamosService.java
src/main/resources/templates/crearCategoria.html
src/main/resources/templates/crearImplemento.html
src/main/resources/templates/listarCategorias.html
src/main/resources/templates/listarDevoluciones.html
src/main/resources/templates/listarInventario.html
src/main/resources/templates/listarPrestamos.html

[X] Add controller prestamos
[X] Add controller devoluciones

Add controller prestamos y devoluciones

---

src/main/java/com/sportgear/sportgear/Controller/CategoriaController.java
src/main/java/com/sportgear/sportgear/Service/CatImplementosService.java
src/main/java/com/sportgear/sportgear/Service/Impl/CatImplementosServiceImpl.java
src/main/resources/templates/listarCategorias.html

[X] Add paginacion listarCategorias

Add paginacion listarCategorias

---

src/main/java/com/sportgear/sportgear/Controller/CategoriaController.java
src/main/java/com/sportgear/sportgear/Controller/InventarioController.java
src/main/java/com/sportgear/sportgear/Controller/RegistroUsuarioControlador.java

[X] Fixed rutas de redireccionamiento

Fixed rutas de redireccionamiento

---

src/main/java/com/sportgear/sportgear/Repository/CatImplementosRepository.java
src/main/java/com/sportgear/sportgear/Repository/DevolucionRepository.java
src/main/java/com/sportgear/sportgear/Repository/EstadosRepository.java
src/main/java/com/sportgear/sportgear/Repository/InventarioRepository.java
src/main/java/com/sportgear/sportgear/Repository/PrestamoRepository.java
src/main/java/com/sportgear/sportgear/Service/CatImplementosService.java
src/main/java/com/sportgear/sportgear/Service/DevolucionesService.java
src/main/java/com/sportgear/sportgear/Service/EstadosService.java
src/main/java/com/sportgear/sportgear/Service/Impl/CatImplementosServiceImpl.java
src/main/java/com/sportgear/sportgear/Service/Impl/DevolucionesServiceImpl.java
src/main/java/com/sportgear/sportgear/Service/Impl/EstadosServiceImpl.java
src/main/java/com/sportgear/sportgear/Service/Impl/InventarioServiceImpl.java
src/main/java/com/sportgear/sportgear/Service/Impl/PrestamosServiceImpl.java
src/main/java/com/sportgear/sportgear/Service/InventarioService.java
src/main/java/com/sportgear/sportgear/Service/PrestamosService.java

Add documentación

---

src/main/java/com/sportgear/sportgear/Controller/CategoriaController.java
src/main/java/com/sportgear/sportgear/Controller/DevolucionesController.java
src/main/java/com/sportgear/sportgear/Controller/EstudianteController.java
src/main/java/com/sportgear/sportgear/Controller/InventarioController.java
src/main/java/com/sportgear/sportgear/Controller/PrestamosController.java

[X] Add documentación controllers Admin y Estudiante

Add documentación controllers Admin y Estudiante

---

src/main/resources/application.properties
src/main/resources/static/Scripts/DevolucionCategoria.js
src/main/resources/static/Scripts/SolicitudCargaDom.js
src/main/resources/templates/listarInventario.html

[X] Update ruta de pagina inventario
[X] Update js solicitud y devolucion

Update ruta de pagina inventario y Update js solicitud y devolucion

---

src/main/resources/templates/devolucion.html
src/main/resources/templates/listarDevoluciones.html

[X] Fixed mostrar el estado Devolución

Fixed mostrar el estado Devolución

---

BD/SportGear.sql

Add Base de Datos

---

src/main/java/com/sportgear/sportgear/Controller/RegistroUsuarioControlador.java
src/main/java/com/sportgear/sportgear/Model/Rol.java
src/main/java/com/sportgear/sportgear/Model/Usuario.java

[X] Eliminando redundancia de código

Eliminando redundancia de código
